backend/todo_lister/src/Entity/TODO.php
<?php

namespace App\Entity;

use App\Repository\TODORepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TODORepository::class)
 */
class TODO
{
    public function __construct()
    {
        $this->setFechaCreacion(new \DateTime('now'));
        $this->setRealizada(false);
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_creacion;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_tope;

    /**
     * @ORM\Column(type="boolean")
     */
    private $realizada;

    /**
     * @ORM\ManyToOne(targetEntity=ListaTODO::class, inversedBy="tODOs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $lista;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getFechaCreacion(): ?\DateTimeInterface
    {
        return $this->fecha_creacion;
    }

    public function setFechaCreacion(\DateTimeInterface $fecha_creacion): self
    {
        $this->fecha_creacion = $fecha_creacion;

        return $this;
    }

    public function getFechaTope(): ?\DateTimeInterface
    {
        return $this->fecha_tope;
    }

    public function setFechaTope(string $fecha_tope): self
    {
        $this->fecha_tope = new \DateTime($fecha_tope);

        return $this;
    }

    public function isRealizada(): ?bool
    {
        return $this->realizada;
    }

    public function setRealizada(bool $realizada): self
    {
        $this->realizada = $realizada;

        return $this;
    }

    public function getLista(): ?ListaTODO
    {
        return $this->lista;
    }

    public function setLista(?ListaTODO $lista): self
    {
        $this->lista = $lista;

        return $this;
    }
}

backend/todo_lister/templates/todoList/lists.html.twig
{% extends "todoList/base_templates/logged.html.twig" %}

{% block admin %}
	<li class="nav-item">
		{% if admin %}
			<a class="nav-link" aria-current="page" href="{{ path('users_view') }}">
				<div><i class="bi bi-people-fill"> Administrar Usuarios</i></div>
			</a>
		{% endif %}
	</li>
{% endblock %}

{% block content %}

<div class="container mt-5 mb-5">
	<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#crearLista" data-bs-whatever="@crear">
		<i class="bi bi-list-task"></i> Añadir Lista</button>
	<div class="table-responsive">
	    <table class="table table-dark table-striped table-bordered">
		  <thead>
		    <tr>
		      <th scope="col">Nombre</th>
		      <th scope="col">Propietario</th>
				{% if admin %}
				<th scope="col">Acciones</th>
				{% endif %}
		    </tr>
		  </thead>

		  <tbody>
	    	{% for list in lists %}
		    <tr>
				<td> <a href="{{ path('todolist_view',{list_id: list.id})  }}">{{ list.nombre }}</a></td>
				<td>{{ list.propietario.username }}</td>
				{% if admin %}
				<td class="col-2">
					<script type="text/javascript">
						$(document).ready(function () {
							$("#updateOwner_form{{list.id}}").submit(function (event) {

								event.preventDefault();

								$.ajax({
									type: "PUT",
									url: event.currentTarget.action,
									data: $("#updateOwner_form{{list.id}}").serialize(),
									dataType: "json",
									encode: true,
								})

								location.reload();
							});
						});
					</script>
						<div class="modal fade" id="modificarPropietario{{list.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
							<div class="modal-dialog ">
								<div class="modal-content bg-dark txt">
									<div class="modal-header">
										<h5 class="modal-title" id="exampleModalLabel">Editar Propietario</h5>
										<button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
									</div>
									<form id="updateOwner_form{{list.id}}" action={{ path('updateListOwner_request',{list_id: list.id}) }} method="post" onsubmit="$('#modificarPropietario{{list.id}}').modal('hide');">
										<div class="modal-body">
											<div class="row justify-content-center mb-4">
												<div class="col-9">
													<label for="inputFecha1" class="form-label txt">Propietario</label>
													<input type="integer" class="form-control" name="propietario" value="{{list.propietario.username}}" required="true">
												</div>
											</div>
										</div>
										<div class="modal-footer">
											<button type="button" class="btn bg-red txt" data-bs-dismiss="modal">Cerrar</button>
											<button type="submit" class="btn btn-primary">Editar</button>
										</div>
									</form>
								</div>
							</div>
						</div>
					<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modificarPropietario{{ list.id }}" data-bs-whatever="@editar">
						<i class="bi bi-pencil-square"></i></button>
				</td>
				{% endif %}
		    </tr>
	    	{% endfor %}
		  </tbody>

		</table>
	</div>

	<!--modals-->
	<div class="modal fade" id="crearLista" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog ">
			<div class="modal-content bg-dark txt">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Añadir Lista</h5>
					<button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<form action="{{ path('createList_request') }}" method="post">
					<div class="modal-body">
						<div class="mb-3">
							<label for="nombre" class="col-form-label">Nombre:</label>
							<input type="string" class="form-control" name="nombre" id="nombre" required="true">
						</div>
						<div class="row justify-content-center mb-4">
							<div class="col-9">
								<label for="inputFecha1" class="form-label txt">Propietario</label>
								{% if admin %}
								<input type="string" class="form-control" name="propietario" required="true">
								{% else %}
								<input type="string" class="form-control" name="propietario" value="{{username}}" required="true">
								{% endif %}
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn bg-red txt" data-bs-dismiss="modal">Cerrar</button>
						<button type="submit" class="btn btn-primary">Añadir</button>
					</div>
				</form>
			</div>
		</div>
	</div>

</div>

{% endblock %}

backend/todo_lister/templates/todoList/todolist.html.twig
{% extends "todoList/base_templates/logged.html.twig" %}

{% block admin %}
	<li class="nav-item">
		{% if admin %}
			<a class="nav-link" aria-current="page" href="{{ path('users_view') }}">
				<div><i class="bi bi-people-fill"> Administrar Usuarios</i></div>
			</a>
		{% endif %}
	</li>
{% endblock %}

{% block content %}

<div class="container mt-5 mb-5">
	{% if not admin or esPropietario %}
	<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#crearTODO" data-bs-whatever="@crear">
		<i class="bi bi-list-task"></i> Añadir TODO</button>
	{% endif %}
	<div class="table-responsive">
	    <table class="table table-dark table-striped table-bordered">
		  <thead>
		    <tr>
		      <th scope="col">Nombre</th>
		      <th scope="col">Fecha Creación</th>
		      <th scope="col">Fecha Tope</th>
				{% if not admin or esPropietario %}
				<th scope="col-3">Completado</th>
				{% endif %}
		    </tr>
		  </thead>

		  <tbody>
	    	{% for todo in todoList %}
		    <tr>
				<td>{{ todo.nombre }}</td>
				<td>{{ todo.fechaCreacion|date('Y-m-d H:i:s') }}</td>
				<td>{{ todo.fechaTope|date('Y-m-d H:i:s') }}</td>
				{% if not admin or esPropietario %}
				<td class="col-3">

					<script type="text/javascript">
						$(document).ready(function () {
							$("#cambiar_estado{{todo.id}}").on('click',function (event) {

								event.preventDefault();

								$.ajax({
									type: "PUT",
									url: event.currentTarget.action,
									data: $("#cambiar_estado{{todo.id}}").serialize(),
									dataType: "json",
									encode: true,
								})

								location.reload();
							});
						});
					</script>
					{% if todo.realizada %}
					<form id="cambiar_estado{{todo.id}}" class="d-flex" action="{{ path('changeStatus_request',{todo_id: todo.id, status: 'pendiente'}) }}" method="post">
						<div class="form-check" type="submit">
							<input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked>
							<label class="form-check-label" for="flexCheckChecked">
							</label>
						</div>
					</form>
					{% else %}
					<form id="cambiar_estado{{todo.id}}" class="d-flex" action="{{ path('changeStatus_request',{todo_id: todo.id, status: 'completada'}) }}" method="post">
						<div class="form-check" type="submit">
							<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
							<label class="form-check-label" for="flexCheckDefault">
							</label>
						</div>
					</form>
					{% endif %}
				</td>
				{% endif %}
		    </tr>
	    	{% endfor %}
		  </tbody>

		</table>
	</div>

	<!--modals-->
	<div class="modal fade" id="crearTODO" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog ">
			<div class="modal-content bg-dark txt">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Añadir TODO</h5>
					<button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<form action="{{ path('createTODO_request',{list_id: lista}) }}" method="post">
					<div class="modal-body">
						<div class="mb-3">
							<label for="nombre" class="col-form-label">Nombre:</label>
							<input type="string" class="form-control" name="nombre" id="nombre" required="true">
						</div>
						<div class="row justify-content-center mb-4">
							<div class="col-9">
								<label for="inputFecha1" class="form-label txt">Fecha Tope</label>
								<input type="date" class="form-control" name="fechaTope" required="true">
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn bg-red txt" data-bs-dismiss="modal">Cerrar</button>
						<button type="submit" class="btn btn-primary">Añadir</button>
					</div>
				</form>
			</div>
		</div>
	</div>

</div>

{% endblock %}

backend/todo_lister/templates/todoList/users.html.twig
{% extends "todoList/base_templates/logged.html.twig" %}

{% block admin %}
	<li class="nav-item">
		{% if admin %}
			<a class="nav-link" aria-current="page" href="{{ path('users_view') }}">
				<div><i class="bi bi-people-fill"> Administrar Usuarios</i></div>
			</a>
		{% endif %}
	</li>
{% endblock %}

{% block content %}

<div class="container mt-5 mb-5">
	<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#crearUsuario" data-bs-whatever="@crear">
		<i class="bi bi-list-task"></i> Añadir Usuario</button>
	<div class="table-responsive">
	    <table class="table table-dark table-striped table-bordered">
		  <thead>
		    <tr>
		      <th scope="col">Nombre</th>
		      <th scope="col">Rol</th>
		    </tr>
		  </thead>

		  <tbody>
	    	{% for user in users %}
		    <tr>
				<td>{{ user.username }}</td>
				<td>{{ user.roles[0] }}</td>
				</td>
		    </tr>
	    	{% endfor %}
		  </tbody>

		</table>
	</div>

	<!--modals-->
	<div class="modal fade" id="crearUsuario" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog ">
			<div class="modal-content bg-dark txt">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Añadir Usuario</h5>
					<button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<form action="{{ path('app_newUser') }}" method="post">
					<div class="modal-body">
						<div class="mb-3">
							<label for="nombre" class="col-form-label">Nombre:</label>
							<input type="string" class="form-control" name="nombre" id="nombre" required="true">
						</div>
						<div class="row justify-content-center mb-4">
							<div class="col-9">
								<label for="rol" class="form-label txt">Rol:</label>
								<input type="string" class="form-control" name="rol" required="true">
							</div>
						</div>
						<div class="row justify-content-center mb-4">
							<div class="col-9">
								<label for="inputPassword" class="form-label txt">Contraseña:</label>
								<input type="password" class="form-control" name="password" id="inputPassword" autocomplete="current-password" required>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn bg-red txt" data-bs-dismiss="modal">Cerrar</button>
						<button type="submit" class="btn btn-primary">Añadir</button>
					</div>
				</form>
			</div>
		</div>
	</div>

</div>

{% endblock %}